# tasks.label_prediction { #operetta_compose.tasks.label_prediction }

`tasks.label_prediction`



## Functions

| Name | Description |
| --- | --- |
| [label_prediction](#operetta_compose.tasks.label_prediction.label_prediction) | Make predictions on the selected wells and write them to the OME-ZARR |

### label_prediction { #operetta_compose.tasks.label_prediction.label_prediction }

`tasks.label_prediction.label_prediction(zarr_url, classifier_path, table_name='regionprops', label_name='nuclei')`

Make predictions on the selected wells and write them to the OME-ZARR

#### Parameters

| Name              | Type   | Description                                        | Default         |
|-------------------|--------|----------------------------------------------------|-----------------|
| `zarr_url`        | str    | Path to an OME-ZARR Image                          | _required_      |
| `classifier_path` | str    | Path to the pickled scikit-learn classifier        | _required_      |
| `table_name`      | str    | Folder name of the measured regionprobs features   | `'regionprops'` |
| `label_name`      | str    | Name of the labels to use for feature measurements | `'nuclei'`      |
