project:
  type: website

website:
  title: "operetta-compose"
  reader-mode: true
  page-footer: "© 2024, DRP-Kispi"
  repo-url: https://github.com/leukemia-kispi/operetta-compose
  repo-actions: [edit, issue]
  favicon: images/operetta-compose_logo.png
  navbar:
    style: "floating"
    search: true
    logo: images/operetta-compose_logo.png
    tools:
      - icon: github
        href: https://github.com/leukemia-kispi/operetta-compose
    left:
        - installation.qmd
        - contributing.qmd
        - text: View in Napari
          href: napari.ipynb
        - api/index.qmd

format:
  html:
    theme:
      light: cosmo
    fontsize: 100%
    css: styles.css
    toc: true

quartodoc:
  style: pkgdown
  dir: api
  package: operetta_compose
  title: API
  parser: google
  sections:
    - title: Fractal tasks
      desc: "Modular processing tasks for the Opera/Operetta microscope and drug response profiling"
      contents:
        - tasks.condition_registration
        - tasks.feature_classification
        - tasks.cell_count_aggregation
        - tasks.spot_detection
